### ISSUE TITLE
Generierung Objekt zur Übergabe an das Frontend

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#10]

**Comment by MarcMD** [comment]
Hier sind die benötigten Datenbankabfragen: 

Gibt aus in welchen Ländern wie viel in über eine bestimmte Airline (z.B. LH) getwittert wird. 
SELECT COUNT(*) AS COUNTER, COUNTRY 
FROM TWEETS_BY_COUNTRY
WHERE AIRLINE='LH'
GROUP BY COUNTRY
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis: 
'106', NULL
'48', 'Deutschland'
'23', 'US & Kanada'
'20', 'Indien'
'12', 'England'


Gibt aus in welchen Ländern wie viel über alle Airlines getwittert wird. 
SELECT COUNT(*) AS COUNTER, COUNTRY 
FROM TWEETS_BY_COUNTRY
GROUP BY COUNTRY
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis: 
'320', 'US & Kanada'
'174', NULL
'49', 'Deutschland'
'20', 'Indien'
'19', 'Japan'


Gibt aus über welche Airlines wie viel in einem bestimmten Land (z.B. Deutschland) getwittert wird. 
SELECT COUNT(*) AS COUNTER, AIRLINE 
FROM TWEETS_BY_COUNTRY
WHERE COUNTRY='US & Kanada'
GROUP BY AIRLINE
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis: 
'158', 'UA'
'130', '4U'
'23', 'LH'
'3', 'BA'
'2', 'AF'


Gibt aus über welche Airlines wie viel in alles Ländern (weltweit) getwittert wird. 
SELECT COUNT(*) AS COUNTER, AIRLINE 
FROM TWEETS_BY_COUNTRY
GROUP BY AIRLINE
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis: 
'286', 'LH'
'279', 'UA'
'171', '4U'
'9', 'AF'
'6', 'AB'

**Comment by MarcMD** [comment]
![photo_2015-07-28_11-36-42](https://cloud.githubusercontent.com/assets/12643802/8928188/f66a9346-351c-11e5-96cc-7b16488992ec.jpg)


Um NULL Werte bei der Anzeige in der GUI (vgl. Screenshot) zu vermeiden, werden die Abfragen folgendermaßen verändert:

Gibt aus in welchen Ländern wie viel in über eine bestimmte Airline (z.B. LH) getwittert wird.
SELECT COUNT(*) AS COUNTER, COUNTRY
FROM TWEETS_BY_COUNTRY
WHERE AIRLINE='LH' AND COUNTRY IS NOT NULL
GROUP BY COUNTRY
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis:
'48', 'Deutschland'
'23', 'US & Kanada'
'20', 'Indien'
'12', 'England'

Gibt aus in welchen Ländern wie viel über alle Airlines getwittert wird.
SELECT COUNT(*) AS COUNTER, COUNTRY
FROM TWEETS_BY_COUNTRY
WHERE COUNTRY IS NOT NULL
GROUP BY COUNTRY
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis:
'320', 'US & Kanada'
'49', 'Deutschland'
'20', 'Indien'
'19', 'Japan'

Gibt aus über welche Airlines wie viel in einem bestimmten Land (z.B. Deutschland) getwittert wird.
SELECT COUNT(*) AS COUNTER, AIRLINE
FROM TWEETS_BY_COUNTRY
WHERE COUNTRY='US & Kanada'
GROUP BY AIRLINE
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis:
'158', 'UA'
'130', '4U'
'23', 'LH'
'3', 'BA'
'2', 'AF'

Gibt aus über welche Airlines wie viel in alles Ländern (weltweit) getwittert wird.
SELECT COUNT(*) AS COUNTER, AIRLINE
FROM TWEETS_BY_COUNTRY
GROUP BY AIRLINE
ORDER BY COUNTER DESC

Beispielhaftes Ergebnis:
'286', 'LH'
'279', 'UA'
'171', '4U'
'9', 'AF'
'6', 'AB'
