### ISSUE TITLE
Implementierung Datenbank

### ISSUE THREAD

**Issue by ChrisKegel2901** [MarcMD/Fallstudie-WWI13AMC-Twitter#11]
Nach der Datenbank Konzeptionierung wird mit der Implementierung begonnen. Issue wird initial erstellt, Beginn ist zu einem späteren Zeitpunkt.

![db](https://cloud.githubusercontent.com/assets/12609702/7870637/fc7209a2-058a-11e5-9762-2f505c669663.png)

**Comment by MarcMD** [comment]
Um die Datenhaltung und den Datenzugriff auf den verschiedenen Geräten der Entwickler zu ermöglichen, soll eine online Datenbank eingerichtet und mit der Anwendung verbunden werden.

**Comment by ChrisKegel2901** [comment]
Die Methode run() aus der Unter-Klasse RemindTask aus der Klasse ThreadHandler, wird dahingehen umprogrammiert, nun nicht mehr alle X Sekunden die Werte auf der Konsole auszugeben, sondern alle X Sekunden die Werte, inklusive Timestamp, auf die Datenbank zu schreiben.

**Comment by MarcMD** [comment]
![20150626_datenbank_bsp-tabelle](https://cloud.githubusercontent.com/assets/12643802/8375201/9396ff0a-1bfb-11e5-9901-a16166eb3a1f.png)

Hier ein Beispiel der geplanten Tabelle. Die "tweet_id" wird als Schlüssel verwendet. Zu jedem Tweet werden "country" und "airline" gespeichert. 

Die laufende Anwendung schreibt eintreffende Tweets in die Datenbank. Über SQL Aggregatfunktionen können die für die Oberfläche benötigten Zahlen dann abgerufen werden.

**Comment by MarcMD** [comment]
Die Tabelle ist nun implementiert und verfügbar, wobei in der Spalte "country" momentan noch Zeitzonen gespeichert werden.

**Comment by ChrisKegel2901** [comment]
Perfekt. Werde mich sobald die Liste der Timezones zur Verfügung steht, um die "Übersetzung" kümmern.

**Comment by MarcMD** [comment]
Die Übersetzung von "timezone" zu "country" wird über die Datenbank realisiert. Hierzu wird die Datenbank folgendermaßen angepasst: 
In der bestehenden Tabelle TWEETS wird die Spalte "country" in "timezone" umbenannt. Es wird außerdem eine Übersetzungstabelle COUNTRIES angelegt: 
TWEETS(timestamp, timezone, airline)
COUNTRIES(timezone, country)

Diese Tabellen können genutzt werden, um eine Sicht (bzw. einen View) zu erstellen, der die für die Darstellung benötigen Daten enthält: 
TWEETS_BY_COUNTRY(timestamp, country, airline)

**Comment by MarcMD** [comment]
Die Sicht (View) kann nun mit "SELECT * FROM TWEETS_BY_COUNTRY" abgerufen werden. Um Ausgaben zu testen, wurden ein paar Werte in die Tabelle COUNTRIES geschrieben. Sobald das Ergebnis von https://github.com/MarcMD/Fallstudie-WWI13AMC-Twitter/issues/15 verfügbar ist, wird die Tabelle um diese Daten angereichert. 
Die Issue "Implementierung Datenbank" kann damit abgeschlossen werden.
