### ISSUE TITLE
Änderung der Tokens

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#18]
Wie in #9 kommuniziert. 

@OJulia Bitte @ChrisKegel2901 die Zugansdaten zur Verfügung stellen bzw. zwecks Handynr. absprechen.

**Comment by Bjoern93** [comment]
@ChrisKegel2901 Infos zum Account kamen per Mail.

**Comment by ChrisKegel2901** [comment]
Wurde implementiert.
