### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#19]
Die GUI kann derzeit nur von @Bjoern93 (OS: Win 8) aufgerufen werden. 
@TanjaDyroff (OS: MAC OS)  & @MarcMD (Linux) erhalten eine Null Pointer Exception. 

@OJulia Kannst du mal testen ob es auf deinem Windows läuft?  

Vorgehen: 
Die sich in gui-primefaces/src/webapp befindende index.xhtml ausführen.

**Comment by MarcMD** [comment]
Lösung des Problems gefunden. 'Enable Project Specific Settings' (Maven, Java EE Integration) in den Projekt Eintstellungen (eclipse) muss gesetzt werden. 
![photo_2015-07-27_19-53-45](https://cloud.githubusercontent.com/assets/12643802/8913406/3c57891a-3499-11e5-93a7-6a37d12a7abd.jpg)
