### ISSUE TITLE
Auswahl Technologien Backend

### ISSUE THREAD

**Issue by ChrisKegel2901** [MarcMD/Fallstudie-WWI13AMC-Twitter#2]
Folgende Techniken müssen evaluiert werden:
- Apache Camel
- Twitter Library - ja 
- Apache Storm - nein
- Datenaltung auf DB ja/nein - ja

**Comment by ChrisKegel2901** [comment]
Link für Apache Storm:
https://www.udacity.com/course/real-time-analytics-with-apache-storm--ud381

**Comment by ChrisKegel2901** [comment]
Habe experimentiert. Ich denke wir werden Apache Storm nicht brauchen. Habe testhalber mal einen Mini-Parier gebastelt, der nach 2 Kriterien die Messages filtert und zählt. War kein Problem. Werde das mal committen dann kannst du nen Blick drauf werfen Tanja.

**Comment by ChrisKegel2901** [comment]
Des Weiteren würde ich die Benutzung einer Datenbank stark präferieren.

**Comment by ChrisKegel2901** [comment]
Für welche Technologien haben wir uns entschieden?

**Comment by Bjoern93** [comment]
Von Frontendseite werden Primefaces, JSF und Java verwendet.
Zur Gestaltung natürlich HTML & CSS.

Am 12. Juni 2015 um 14:13 schrieb ChrisKegel2901 <notifications@github.com>:
