### ISSUE TITLE
Systemanalyse und Entwurf

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#4]

**Comment by MarcMD** [comment]
Im Rahmen der Anfoderungsanalysoe wurden folgende Mockups entwickelt, die nicht Design oder Layout vorgeben, sondern eine Vorstellung der Funktionen den Programms vermitteln sollen. 
![20150623_mockup_screen1](https://cloud.githubusercontent.com/assets/12643802/8307699/55a71faa-19c0-11e5-9e7c-f6742612e3ea.png)
![20150623_mockup_screen2](https://cloud.githubusercontent.com/assets/12643802/8307701/57ac0c02-19c0-11e5-8ab5-db3905c16bbd.png)

**Comment by MarcMD** [comment]
Das Ergebnis der Anforderungsanalyse kann im Wiki (https://github.com/MarcMD/Fallstudie-WWI13AMC-Twitter/wiki/Anforderungsanalyse) abgerufen werden.
