### ISSUE TITLE
Grobes Komponentendiagramm 

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#5]
Erstellung eines groben Komponentendiagramms für 

1) Backend 
2) Frontend 

Hinweis: Bitte nach Erstellung des Komponentendiagramms für das Backend an @Bjoern93 assignen!

**Comment by ChrisKegel2901** [comment]
![komponenten_diagramm-2](https://cloud.githubusercontent.com/assets/12609702/7870398/647e1a9c-0589-11e5-9632-0bdbd73db9bc.png)

**Comment by ChrisKegel2901** [comment]
Komponenten Diagramm überarbeitet.
![komponenten_backend](https://cloud.githubusercontent.com/assets/12609702/7897487/9a2c8390-06dd-11e5-8192-727433a5980b.png)

**Comment by ChrisKegel2901** [comment]
Oben erwähntes Komponentendiagramm wird nach der heutigen Session abgeändert. 

Ich warte damit noch bis zur Fertigstellung der entsprechenden Klassen, damit es nicht nochmal neu gemacht werden muss. 

@MarcMD Exakte Positionierung der DB im Programm muss geklärt werden. Ich denke Backlog Creator, alias save()-Methode, wird direkt in die DB schreiben und Object Creator anstatt des Thread Handlers die Werte abrufen?

**Comment by MarcMD** [comment]
@ChrisKegel2901 Ich habe eine Klasse "DBConnection" erstellt. Dort werden die Verbindungen zu unserer online Datenbank in einem Pool bereit gehalten, sodass man nicht an jeder Stelle im Code Verbindungen aufbauen muss (was das Programm langsamer machen würde). Momentan werden diese Verbindungen nur in der save()-Methode genutzt, um die Tweets in die Datenbank zu schreiben. Das Abrufen der Werte sehe ich auch im Object Creator.

**Comment by ChrisKegel2901** [comment]
![komponenten_backend-2](https://cloud.githubusercontent.com/assets/12609702/8392287/f8685ff6-1ce5-11e5-8538-71299c7972d8.png)

Überarbeitetes Komponentendiagramm.
@MarcMD @TanjaDyroff

**Comment by Bjoern93** [comment]
![komponenten](https://cloud.githubusercontent.com/assets/12391701/8497695/7d4590a2-217f-11e5-9b17-586921ab4793.png)
