### ISSUE TITLE
UML-Diagramm

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#6]

**Comment by ChrisKegel2901** [comment]
![diagramm](https://cloud.githubusercontent.com/assets/12609702/8305828/f227e8ea-19b2-11e5-9468-7fa63b54fb70.png)

Initial. Wird ggf. nach DB-Implementation noch angepasst.

**Comment by ChrisKegel2901** [comment]
![model](https://cloud.githubusercontent.com/assets/12609702/8392247/a344c7fe-1ce4-11e5-9e2f-d8f27f27c0bc.gif)

Neues UML-Diagramm @MarcMD

**Comment by ChrisKegel2901** [comment]
![model](https://cloud.githubusercontent.com/assets/12609702/8392355/9867a5be-1ce8-11e5-9b53-386871c0d913.png)

TimezoneConverter entfernt. Verhalten wird über DB realisiert.

**Comment by Bjoern93** [comment]
# UML-Diagramm Frontend

![uml-frontend](https://cloud.githubusercontent.com/assets/12391701/8434301/f0b22f78-1f4a-11e5-8b4a-a5a2ec257c8c.png)

**Comment by Bjoern93** [comment]
UML-Diagramme liegen komplett vor
