### ISSUE TITLE
Abrufen Tweets 

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#7]

**Comment by ChrisKegel2901** [comment]
Twitteranbindung über die Twitter API "Twitter hbc" alias Twitter hosebound client wurde initial getestet. Derzeit noch ohne wirkliche Funktion, Nachrichten werden derzeit nur gefiltert und auf der Konsole ausgegeben.

**Comment by ChrisKegel2901** [comment]
Daten werden jetzt zwischengespeichert in .txt-Dokument zur Übergabe an den Thread Handler.

Format: AIRLINE,VALUE

Werte werden gezählt. Durch Threading beliebig erweiterbar.

**Comment by MarcMD** [comment]
Issue wird geschlossen. Restliche Datenhaltunsaspekte - wie das Anbinden einer Datenbank - wird in der Issue "Implementierung Datenbank" (https://github.com/MarcMD/Fallstudie-WWI13AMC-Twitter/issues/11) behandelt.
