### ISSUE TITLE
JSON - Object

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#8]
Umwandlung JSON-String in Java-Objekt

**Comment by ChrisKegel2901** [comment]
Ich denke dieses Issue ist nicht notwendig, es beschreibt im Grunde nur alle anderen Issues des Milestones und sollte demnach mit #10 zeitgleich beendet sein. @TanjaDyroff wie siehst du das?

**Comment by TanjaDyroff** [comment]
Sehe das ebenfalls so.
