### ISSUE TITLE
Analyse der Tweets

### ISSUE THREAD

**Issue by Bjoern93** [MarcMD/Fallstudie-WWI13AMC-Twitter#9]

**Comment by ChrisKegel2901** [comment]
Analyse initial implementiert. Derzeit Filterung nach "#LH" und "Lufthansa" mit nachfolgenden Message Processing auf den JSON-String. String wird an den Leerzeichen gesplittet, dann je nachdem entweder LH oder Lufthansa auf der Konsole ausgegeben. Gleichzeitig wird die Integer-Variable "LH" inkrementiert.

**Comment by ChrisKegel2901** [comment]
Analyse weitestgehend implementiert. Filterung findet nun nach beliebigen Strings statt. Derzeit "Lufthansa" + "#LG", "Germanwings" + "#4U" und "Air France" + "#AF". Werte werden gezählt und zwischengespeichert. Vorbereitung für Value Processing implementiert.

**Comment by ChrisKegel2901** [comment]
In der nächsten Iteration wird das Konzept zusätzlich um die Analyse von Timezones erweitert.

**Comment by ChrisKegel2901** [comment]
![dateiformat](https://cloud.githubusercontent.com/assets/12609702/8372108/1de6c922-1be0-11e5-963a-48e075f6d657.png)

Anbei das überarbeitete Konzept/Dateiformat für die Textdateien, welche zur Rückgabe an den ThreadHandler verwendet werden.

**Comment by ChrisKegel2901** [comment]
![dateiformat](https://cloud.githubusercontent.com/assets/12609702/8372147/ccc4b9e0-1be0-11e5-9702-15a1446d444e.png)

Anbei das überarbeitete Konzept/Dateiformat für die Textdateien, welche zur Rückgabe an den ThreadHandler verwendet werden.

**Comment by ChrisKegel2901** [comment]
Code wurde umfangreich geändert. Nun erfolgt auch eine Analyse der Timezone und der Timestamp zur späteren Übergabe an die DB. Im Optimalfall wird die oben erwähnte Textdatei nicht mehr benötigt, direktes Schreiben der Threads in die DB ist angedacht.

**Comment by ChrisKegel2901** [comment]
In meinen Augen ist die Implementierung zur Analyse der Tweets abgeschlossen. @MarcMD wie siehst Du das?

**Comment by Bjoern93** [comment]
Kannst du bitte nochmal prüfen warum z.T. so wenige Tweets rein kommen? 

Ggf. könnte eine andere API benötigt werden. 

 

Bitte auch noch die Token ändern.

 

Von: ChrisKegel2901 [mailto:notifications@github.com] 
Gesendet: Dienstag, 7. Juli 2015 09:42
An: MarcMD/Fallstudie-WWI13AMC-Twitter
Cc: Bjoern93
Betreff: Re: [Fallstudie-WWI13AMC-Twitter] Analyse der Tweets (#9)

 

In meinen Augen ist die Implementierung zur Analyse der Tweets abgeschlossen. @MarcMD <https://github.com/MarcMD>  wie siehst Du das?

**Comment by ChrisKegel2901** [comment]
Bin ich schon länger am suchen, werde versuchen einen Grund zu finden. Token wird geändert. Wurde ein entsprechender Twitter Account erstellt? Könnte das notfalls auch über meinen Twitter Account abwickeln.

**Comment by Bjoern93** [comment]
@OJulia kannst du Christian bitte die Zugangsdaten geben? 

 

Von: ChrisKegel2901 [mailto:notifications@github.com] 
Gesendet: Dienstag, 7. Juli 2015 09:47
An: MarcMD/Fallstudie-WWI13AMC-Twitter
Cc: Bjoern93
Betreff: Re: [Fallstudie-WWI13AMC-Twitter] Analyse der Tweets (#9)

 

Bin ich schon länger am suchen, werde versuchen einen Grund zu finden. Token wird geändert. Wurde ein entsprechender Twitter Account erstellt? Könnte das notfalls auch über meinen Twitter Account abwickeln.

**Comment by MarcMD** [comment]
Ich bin auch der Meinung, dass wir noch kontrollieren sollten, ob wir alle Tweets bekommen oder zu wenige Tweets bei uns reinkommen. Wenn wir zu wenige Tweets bekommen sollten wir unterschen warum das so ist - wie Bjoern gesagt hat, evtl. eine andere API.

**Comment by ChrisKegel2901** [comment]
Wurde verifiziert. Fehler ist behoben.
